export const CURRENT_TERMS_EFFECTIVE_DATE = "2023-06-09";
export const CURRENT_PRIVACY_EFFECTIVE_DATE = "2023-06-09";
export const CURRENT_COOKIES_EFFECTIVE_DATE = "2023-06-09";
export const CURRENT_AGE_REQUIREMENT_STATEMENT =
  "I am at least 18 years of age";
